services:
  php-fpm:
    build: php
    volumes:
      - ./app:/var/www/app
    links:
        - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
        - php
#
#  db:
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test
#      MYSQL_USER: prv
#      MYSQL_PASSWORD: 12qwaszx
